### ISSUE TITLE
Add content to Home Page

### ISSUE THREAD

**Issue by theflametrooper** [extramundane/extramundane.github.io#10]
- [x] Display info about how we get beginners open source contributions
- [ ] Display quotes from past users - NA until first project complete
- [x] Make more user friendly with re-design
- [ ] Add 3 steps
- [ ] Add Popular Projects

**Comment by Munsterberg** [comment]
Im working on some redesigns for the home page and will add content as I go. I have scraped a few concepts already, might take a while. I will update you regularly on slack.

**Comment by Munsterberg** [comment]
Still working on a redesign, just having a rough go without photoshop. Will update you on slack when I get a chance for the redesign.
