### ISSUE TITLE
Project Managers Page

### ISSUE THREAD

**Issue by theflametrooper** [extramundane/extramundane.github.io#13]
- [x] Review to decide on what issue reporting software to use. (Trello, Github Issues)
- [x] Make sure we have included everything we need so we don't have to constantly help pms.
- [x] Fix Bug where we used HTML instead of Jade

**Comment by Munsterberg** [comment]
Should receive an email from my friend later today, so expect issue to be closed by the end of the day

**Comment by Munsterberg** [comment]
He said everything looks good, and just to add any info as we go (which I already figured). Closing issue
