### ISSUE TITLE
Publicity at Launch

### ISSUE THREAD

**Issue by theflametrooper** [extramundane/extramundane.github.io#34]
_Post on Subreddits:_ FreeCodeCamp
_DevWars Slack:_ #critique channel
_FreeCodeCamp:_ Forum, Main, CoreTeam, Casual

Please add any more suggestions @alayek @Munsterberg for how we can publicise ExtraMundane without heavily self promoting :wink:

**Comment by alayek** [comment]
I am not sure if you should publicize on FreecodeCamp subreddit. We are a non-profit, right?

I think you should also publicize on Twitter. Twitter is a place for devs to hang out. If it get right retweets - you never know.

Also, record some YouTube tutorial and post online. Then, once we have our back-end ready, we might have a tiny chance of posting on Hackernews.
